import App from './serverApp';
import AuthRoute from './app/route/auth.route';
import UsersRoute from './app/route/users.route';
import ClientsRoute from './app/route/clients.route';
import EmploymentHistoryRoute from './app/route/employment_history.route';
import NotificationRoute from './app/route/notifications.route';
import ModulesRoute from './app/route/modules.route';
import AuthMiddlewareRoute from './app/route/auth_middleware.route';
import CertificationProviderRoute from './app/route/certification_providers.route';
import RolesRoute from './app/route/roles.route';
import SkillSetRoute from './app/route/skill_set.route';
import UsersAdminMetricsRoute from './app/route/users_admin_metrics.route';
import UsersLearnerMetricsRoute from './app/route/users_learner_metrics.route';
import NotificationPreferenceRoute from './app/route/notification_preference.route';
import CertificationsRoute from './app/route/user_certifications.route';
import UserProfilesRoute from './app/route/user_profiles.route';
import UploadFileRoute from './app/route/upload_file.route';
import datahistoryRoute from './app/route/userdatahistory.route';
import CompanyRoute from './app/route/company.route';
import  TemplateRoute  from './app/route/template.route';

const routes = [];
routes.push(new UsersRoute());
routes.push(new AuthRoute());
routes.push(new ClientsRoute());
routes.push(new EmploymentHistoryRoute());
routes.push(new NotificationRoute());
routes.push(new ModulesRoute());
routes.push(new AuthMiddlewareRoute());
routes.push(new CertificationProviderRoute());
routes.push(new RolesRoute());
routes.push(new SkillSetRoute());
routes.push(new UsersAdminMetricsRoute());
routes.push(new UsersLearnerMetricsRoute());
routes.push(new CertificationsRoute());
routes.push(new UserProfilesRoute());
routes.push(new NotificationPreferenceRoute());
routes.push(new UploadFileRoute());
routes.push(new CompanyRoute());
routes.push(new datahistoryRoute());
routes.push(new TemplateRoute());

const app = new App(routes);
app.listen();
