import { config } from 'dotenv';
config({ path: `.env` });

export const CREDENTIALS = process.env.CREDENTIALS === 'true';
export const {
  NODE_ENV,
  REPORTS_PORT,
  BATCH_PORT,
  COURSES_PORT,
  USERS_SERVICE_PORT,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_DATABASE,
  SECRET_KEY,
  LOG_FORMAT,
  LOG_DIR,
  ORIGIN,
  GITHUB_TOKEN,
  GIT_URL,
  GIT_LOCAL_PATH,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_DATABASE,
  USERS_SERVICE_URL,
  HOST_IP,
  REPORTS_SERVICE_PORT,
COURSES_SERVICE_PORT ,
BATCHES_SERVICE_PORT,
BOT_SERVICE_PORT,
  MS_TEAMS_SERVICE_PORT,
  COURSES_SERVICE_URL,
  BATCHES_SERVICE_URL,
  REPORTS_SERVICE_URL,
  BOT_SERVICE_URL
} = process.env;

export const AUTH_PATH = '/api/users/getAuth';
